### PR TITLE
fixes

### LINKED ISSUE #30: "API resolved without sending a response" appearing on every route despite the API routes working fine.
I recently switched from an Express server to NextJS's API pages, and I love the way this repo helps with that, so thank you!

That said, all of my API routes are logging "API resolved without sending a response". [This](https://github.com/zeit/next.js/issues/10439) issue was posted 3 days ago in nextjs's issues and was closed the next day with [this](https://github.com/zeit/next.js/issues/10439#issuecomment-583214126) comment being the solution to it. I was wondering if the solution could be implemented into this repo. It looks like the OP was using async/await and the comment that solved the problem recommended returning a Promise instead. In my particular case, all my my routes are printing the message, regardless of if they are asynchronous or not. One example is the following:

```
import connect from "next-connect"
import common from "../../../middleware/common/"
import keys from "../../../config/keys"

const handler = connect()
handler.use(common)

handler.post((req, res) => {
  return res.status(200).send(keys.googleMapsKey)
})

export default handler
```

It's possible my problem lies elsewhere, but since all of my routes are going through next-connect, I figured this might be something to be looked at within the repo.

### PR DESCRIPTION
**Pull request by throwarray**
fixes #30

### CODE REVIEW

**Comment by throwarray** [comment]
Also, I'm curious what influenced the decision to remove `(err,req,res,next)` styled middleware. Perhaps it could be added again?

**Comment by hoangvvo** [comment]
Thanks @throwarray, I will review this PR soon. About the removal of `(err, req, res, next)`:

- This allows continuation after the error is throw (If needed).

**Previous**

```javascript
app.use(thisWork)
app.use(thisThrow) // throw here
app.use(thisWork1) // always skip
app.use(thisWork2) // always skip
app.use(anerrormiddleware) // handle error
// it's over, no way back
```

**Now**

```javascript
app.use(thisWork)
app.use(thisThrow) // throw here
// simply calling .onError here and if next is called...
app.use(thisWork1) // may continue
app.use(thisWork2) // may continue
```

- It is awkwark always having to remember to put the error middleware at the end. If one forget:

```javascript
app.use(thisWork) 
app.use(anerrormiddleware) // skip because there is no error
app.use(thisThrow) // throw here
app.use(thisWork1) // skip. uh oh where is the error middleware
app.use(thisWork2) // skip. oh no
```
- The only way this can determine if a middleware is an error middleware is by looking at its number of argument (4 of them). This is unreliable. What if I do not need (eslint will complain if `next` is never used) or forget `next` argument?

**Comment by hoangvvo** [comment]
I think one thing I miss is the convenience of using multiple error middleware.
```
app.use(errorLogger)
app.use(anotherErrorLoggerBcWhyNot)
app.use(errorResponse)
```
Perhaps a future version will accept an array of middleware for `onError`

**Comment by hoangvvo** [comment]
Thanks @throwarray, close in favor of #38

**Comment by throwarray** [comment]
@hoangvvo it does seem better to have it just be the apply method. 
You should consider rewriting the 'next' function however because at the moment you have dangling promise errors. There's no catch on the next();. Or is that intentional?

**Comment by throwarray** [comment]
```js
handler.get(async function () {
    await new Promise(function (resolve, reject) {
        setTimeout(function () { reject(new Error('error')) }, 100)
    })
})
```

**Comment by hoangvvo** [comment]
@throwarray This is definitely a bug. I just reproduce it locally. I will try to get a fix in

**Pull request closed without merging**
