### PR TITLE
Fix handler return type

### LINKED ISSUE #74: RequestHandler return type
Documentation states, that `get` can be called with `async` function. `async` always returns a promise. Am I correct to assume, that `RequestHandler` should have type of `void | Promise<void>` in this case, or maybe generic `<X: any>` like Trouter? The same with `ErrorHandler`.

PR welcome?

### PR DESCRIPTION
**Pull request by Tymek**
closes #74

### CODE REVIEW

**Comment by Tymek** [comment]
Should I also add this to changelog and bump version?

**Comment by hoangvvo** [comment]
I make some changes as I commented: Change the handler functions return type to `Promise<any> | `any` (even though I would have preferred `Promise<void> | void`

I will merge it just for now because the error is probably holding back a lot of people. If you think there is still a problem, let's open another PR.

**Comment by hoangvvo** [comment]
Thanks @Tymek.

> btw, really appreciate you naming the branch ‘main’. Will probably change mine to that too soon.

**Comment by Tymek** [comment]
Well, it's not for this popular current reason. I still keep my `master` branch as "master copy". Like in "master record". I had problems with pull-bot overriding my work on forked repositories. I usually PR feature branch containing squashed commits and keep originals on `main`. Just my workflow convention

**Comment by hoangvvo** [comment]
> > > btw, really appreciate you naming the branch ‘main’. Will probably change mine to that too soon.
> 
> Well, it's not for this popular current reason. I still keep my `master` branch as "master copy". Like in "master record". I had problems with pull-bot overriding my work on forked repositories. I usually PR feature branch containing squashed commits and keep originals on `main`. Just my workflow convention, only for working on forks. No need to fix what ain't broken. I'd reverse names if original has it the other way around

Ah I see, sorry for the confusion.

**Pull request merged**
