### PR TITLE
docs(README): fix typo

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by hoangvvo** [comment]
It is just a silly slang. https://www.urbandictionary.com/define.php?term=Smol

**Comment by vvo** [comment]
👍 I saw another one btw:

**Comment by hoangvvo** [comment]
Feel free to update this PR. I can merge it.

**Comment by hoangvvo** [comment]
I fixed the typo. will merge it if it looks good to you too

**Comment by vvo** [comment]
LGTM :)

**Pull request merged**
